# 📊 Pandas EAD 3 - Leitura e Exportação de Dados

Este notebook aborda como ler dados de diferentes fontes e exportar resultados com Pandas.

## 📚 Conceitos abordados:
- Leitura de arquivos CSV
- Leitura de arquivos Excel
- Leitura de arquivos JSON
- Exportação para CSV
- Exportação para Excel
- Exportação para JSON
- Leitura de dados da web

## 🎯 Objetivo:
Ao final deste módulo, você será capaz de importar e exportar dados em diferentes formatos.

**Vamos começar!** 🚀

## 1. Criando Dados de Exemplo

Vamos criar alguns dados para praticar:

In [11]:
import pandas as pd
import numpy as np

# Criando dados de alunos
dados_alunos = {
    'Nome': ['Ana Silva', 'João Santos', 'Maria Oliveira', 'Pedro Costa', 'Carla Lima',
             'Roberto Alves', 'Juliana Ferreira', 'Carlos Souza', 'Patrícia Rocha', 'André Pereira'],
    'Idade': [25, 30, 28, 35, 22, 29, 26, 31, 27, 33],
    'Curso': ['Python', 'Java', 'Python', 'JavaScript', 'Python', 
              'Java', 'JavaScript', 'Python', 'Java', 'JavaScript'],
    'Nota': [8.5, 9.0, 7.5, 9.5, 8.0, 8.5, 9.0, 7.0, 9.5, 8.0],
    'Faltas': [2, 0, 3, 1, 2, 1, 0, 4, 1, 2]
}

df_alunos = pd.DataFrame(dados_alunos)
print("Dados dos Alunos:")
print(df_alunos)

Dados dos Alunos:
               Nome  Idade       Curso  Nota  Faltas
0         Ana Silva     25      Python   8.5       2
1       João Santos     30        Java   9.0       0
2    Maria Oliveira     28      Python   7.5       3
3       Pedro Costa     35  JavaScript   9.5       1
4        Carla Lima     22      Python   8.0       2
5     Roberto Alves     29        Java   8.5       1
6  Juliana Ferreira     26  JavaScript   9.0       0
7      Carlos Souza     31      Python   7.0       4
8    Patrícia Rocha     27        Java   9.5       1
9     André Pereira     33  JavaScript   8.0       2

## 2. Exportando Dados

### Exportando para CSV:

In [12]:
# Exportando para CSV (sem índice)
df_alunos.to_csv('alunos.csv', index=False)
print("Arquivo 'alunos.csv' criado com sucesso!")

# Exportando para CSV com separador diferente
df_alunos.to_csv('alunos_semicolon.csv', sep=';', index=False)
print("Arquivo 'alunos_semicolon.csv' criado com sucesso!")

Arquivo 'alunos.csv' criado com sucesso!
Arquivo 'alunos_semicolon.csv' criado com sucesso!

### Exportando para Excel:

In [14]:
# Exportando para Excel
df_alunos.to_excel('alunos.xlsx', index=False, sheet_name='Alunos')
print("Arquivo 'alunos.xlsx' criado com sucesso!")

# Exportando múltiplas planilhas
with pd.ExcelWriter('alunos_multiplas.xlsx') as writer:
    df_alunos.to_excel(writer, sheet_name='Dados_Completos', index=False)
    
    # Criando um resumo por curso
    resumo_curso = df_alunos.groupby('Curso').agg({
        'Nota': ['mean', 'max', 'min'],
        'Faltas': 'mean'
    })
    resumo_curso.to_excel(writer, sheet_name='Resumo_Curso')
    
print("Arquivo 'alunos_multiplas.xlsx' criado com sucesso!")

Arquivo 'alunos.xlsx' criado com sucesso!
Arquivo 'alunos_multiplas.xlsx' criado com sucesso!

### Exportando para JSON:

In [15]:
# Exportando para JSON
df_alunos.to_json('alunos.json', orient='records', indent=2)
print("Arquivo 'alunos.json' criado com sucesso!")

# Diferentes orientações de JSON
df_alunos.to_json('alunos_split.json', orient='split', indent=2)
print("Arquivo 'alunos_split.json' criado com sucesso!")

Arquivo 'alunos.json' criado com sucesso!
Arquivo 'alunos_split.json' criado com sucesso!

## 3. Lendo Dados

### Lendo arquivos CSV:

In [16]:
# Lendo CSV criado anteriormente
df_lido_csv = pd.read_csv('alunos.csv')
print("Dados lidos do CSV:")
print(df_lido_csv)

# Lendo CSV com separador diferente
df_lido_csv_sem = pd.read_csv('alunos_semicolon.csv', sep=';')
print("\nDados lidos do CSV com separador ;:")
print(df_lido_csv_sem)

Dados lidos do CSV:
               Nome  Idade       Curso  Nota  Faltas
0         Ana Silva     25      Python   8.5       2
1       João Santos     30        Java   9.0       0
2    Maria Oliveira     28      Python   7.5       3
3       Pedro Costa     35  JavaScript   9.5       1
4        Carla Lima     22      Python   8.0       2
5     Roberto Alves     29        Java   8.5       1
6  Juliana Ferreira     26  JavaScript   9.0       0
7      Carlos Souza     31      Python   7.0       4
8    Patrícia Rocha     27        Java   9.5       1
9     André Pereira     33  JavaScript   8.0       2

Dados lidos do CSV com separador ;:
               Nome  Idade       Curso  Nota  Faltas
0         Ana Silva     25      Python   8.5       2
1       João Santos     30        Java   9.0       0
2    Maria Oliveira     28      Python   7.5       3
3       Pedro Costa     35  JavaScript   9.5       1
4        Carla Lima     22      Python   8.0       2
5     Roberto Alves     29        Java   8.5       1
6  Juliana Ferreira     26  JavaScript   9.0       0
7      Carlos Souza     31      Python   7.0       4
8    Patrícia Rocha     27        Java   9.5       1
9     André Pereira     33  JavaScript   8.0       2

### Lendo arquivos Excel:

In [17]:
# Lendo Excel
df_lido_excel = pd.read_excel('alunos.xlsx', sheet_name='Alunos')
print("Dados lidos do Excel:")
print(df_lido_excel)

# Lendo Excel com múltiplas planilhas
arquivo_excel = pd.ExcelFile('alunos_multiplas.xlsx')
df_completo = pd.read_excel(arquivo_excel, sheet_name='Dados_Completos')
df_resumo = pd.read_excel(arquivo_excel, sheet_name='Resumo_Curso')

print("\nResumo por Curso:")
print(df_resumo)

Dados lidos do Excel:
               Nome  Idade       Curso  Nota  Faltas
0         Ana Silva     25      Python   8.5       2
1       João Santos     30        Java   9.0       0
2    Maria Oliveira     28      Python   7.5       3
3       Pedro Costa     35  JavaScript   9.5       1
4        Carla Lima     22      Python   8.0       2
5     Roberto Alves     29        Java   8.5       1
6  Juliana Ferreira     26  JavaScript   9.0       0
7      Carlos Souza     31      Python   7.0       4
8    Patrícia Rocha     27        Java   9.5       1
9     André Pereira     33  JavaScript   8.0       2

Resumo por Curso:
   Unnamed: 0      Nota Unnamed: 2 Unnamed: 3    Faltas
0         NaN      mean        max        min      mean
1       Curso       NaN        NaN        NaN       NaN
2        Java         9        9.5        8.5  0.666667
3  JavaScript  8.833333        9.5          8         1
4      Python      7.75        8.5          7      2.75

### Lendo arquivos JSON:

In [18]:
# Lendo JSON
df_lido_json = pd.read_json('alunos.json')
print("Dados lidos do JSON:")
print(df_lido_json)

Dados lidos do JSON:
               Nome  Idade       Curso  Nota  Faltas
0         Ana Silva     25      Python   8.5       2
1       João Santos     30        Java   9.0       0
2    Maria Oliveira     28      Python   7.5       3
3       Pedro Costa     35  JavaScript   9.5       1
4        Carla Lima     22      Python   8.0       2
5     Roberto Alves     29        Java   8.5       1
6  Juliana Ferreira     26  JavaScript   9.0       0
7      Carlos Souza     31      Python   7.0       4
8    Patrícia Rocha     27        Java   9.5       1
9     André Pereira     33  JavaScript   8.0       2

## 4. Lendo Dados da Web

O Pandas pode ler dados diretamente da web:

In [19]:
# Lendo dados de uma URL (exemplo com dados de exemplo)
url = 'https://raw.githubusercontent.com/datasciencecampus/datasets/master/remote_sensing/2016-05-03_188_road.csv'
try:
    df_url = pd.read_csv(url)
    print("Dados lidos da URL:")
    print(df_url.head())
except:
    print("Erro ao ler URL. Verifique sua conexão com a internet.")
    
# Lendo tabelas HTML da web
try:
    # Exemplo com tabela da Wikipedia
    url_wiki = 'https://pt.wikipedia.org/wiki/Lista_de_estados_do_Brasil_por_popula%C3%A7%C3%A3o'
    tabelas = pd.read_html(url_wiki)
    print(f"\nEncontradas {len(tabelas)} tabelas na página")
    print("Primeira tabela:")
    print(tabelas[0].head())
except:
    print("Erro ao ler tabelas da web.")

Erro ao ler URL. Verifique sua conexão com a internet.
Erro ao ler tabelas da web.

## 5. Exercícios - Nível 3

Pratique a leitura e exportação de dados:

### Exercício 1: Exportando Dados
Crie um DataFrame com dados de produtos (Nome, Preço, Estoque, Categoria) e exporte em:
1. CSV (com separador vírgula)
2. CSV (com separador ponto e vírgula)
3. Excel com duas planilhas (uma com dados completos e outra com resumo por categoria)

In [22]:
import pandas as p
# Criando os produtos
dados = {
    "Nome": ["Arroz", "Feijão", "Macarrão", "leite", "Café"],
    "Preço": [25.00, 8.50, 5.00, 6.50, 15.00],
    "Estoque": [20, 30, 15, 25, 10],
    "Categoria": ["Alimento", "Alimento", "Alimento", "Bebida", "Bebida"]
}
df = pd.DataFrame(dados)


df

       Nome  Preço  Estoque Categoria
0     Arroz   25.0       20  Alimento
1    Feijão    8.5       30  Alimento
2  Macarrão    5.0       15  Alimento
3     leite    6.5       25    Bebida
4      Café   15.0       10    Bebida

In [23]:
# Exportando para CSV com separador diferente
df.to_csv('Produtos1.csv', sep=',', index=False)
print("Arquivo 'Produtos1.csv' criado com sucesso!")

Arquivo 'Produtos1.csv' criado com sucesso!

In [24]:
df.to_csv('Produtos2.csv', sep=';', index=False)
print("Arquivo 'Produtos2.csv' criado com sucesso!")

Arquivo 'Produtos2.csv' criado com sucesso!

### Exercício 2: Lendo Dados
Leia os arquivos que você criou no exercício anterior e:
1. Leia o CSV com vírgula
2. Leia o CSV com ponto e vírgula
3. Leia cada planilha do Excel separadamente

In [25]:
# Lendo CSV criado anteriormente
df_lido_csv = pd.read_csv('Produtos1.csv')
print("Dados lidos do CSV:")
print(df_lido_csv)

# Lendo CSV com separador diferente
df_lido_csv_sem = pd.read_csv('Produtos2.csv', sep=';')
print("\nDados lidos do CSV com separador ;:")
print(df_lido_csv_sem)

Dados lidos do CSV:
       Nome  Preço  Estoque Categoria
0     Arroz   25.0       20  Alimento
1    Feijão    8.5       30  Alimento
2  Macarrão    5.0       15  Alimento
3     leite    6.5       25    Bebida
4      Café   15.0       10    Bebida

Dados lidos do CSV com separador ;:
       Nome  Preço  Estoque Categoria
0     Arroz   25.0       20  Alimento
1    Feijão    8.5       30  Alimento
2  Macarrão    5.0       15  Alimento
3     leite    6.5       25    Bebida
4      Café   15.0       10    Bebida

### Exercício 3: Manipulando Dados Lidos
Leia o arquivo 'alunos.csv' criado anteriormente e:
1. Calcule a média de notas por curso
2. Encontre os 3 alunos com maior nota
3. Crie um novo DataFrame com apenas alunos com nota > 8
4. Exporte este novo DataFrame para um arquivo JSON

In [27]:
# Seu código aqui
media_curso =df_alunos.groupby('Curso')['Nota'].mean()
print(f"A média de nota por curso é {media_curso}")

A média de nota por curso é Curso
Java          9.000000
JavaScript    8.833333
Python        7.750000
Name: Nota, dtype: float64

In [29]:
df_alunos.sort_values(by='Nota', ascending=False).head(3)

               Nome  Idade       Curso  Nota  Faltas
8    Patrícia Rocha     27        Java   9.5       1
3       Pedro Costa     35  JavaScript   9.5       1
6  Juliana Ferreira     26  JavaScript   9.0       0

### Exercício 4: Lendo da Web
Tente ler dados de uma fonte pública na web:
1. Encontre uma URL com dados CSV públicos
2. Leia os dados com Pandas
3. Faça uma análise básica (head, describe, info)
4. Exporte os dados filtrados para Excel

In [0]:
# Seu código aqui

### Exercício 5: Desafio Final
Crie um pipeline completo:
1. Leia um arquivo CSV (pode ser o alunos.csv)
2. Faça uma análise (calcule estatísticas, crie novas colunas)
3. Salve os resultados em um arquivo Excel com duas planilhas:
   - 'Dados_Processados': com os dados originais + novas colunas
   - 'Resumo': com estatísticas agrupadas por categoria

In [0]:
# Seu código aqui